package:
  name: bioconductor-limma
  version: 3.26.3
source:
  fn: limma_3.26.3.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/limma_3.26.3.tar.gz
  md5: 9543aec322a1177163cbd689800552d5
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r >=2.3.0'
  run:
    - 'r >=2.3.0'
test:
  commands:
    - '$R -e "library(''limma'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/limma.html
  license: 'GPL (>=2)'
  summary: 'Data analysis, linear models and differential expression for microarray
    data.'
