package:
  name: seer
  version: 1.1.4

source:
  fn: seer_v1.1.4.tar.gz
  url: https://github.com/johnlees/seer/releases/download/v1.1.4/seer_v1.1.4.tar.gz
  md5: b688fc43107ff6724a7e23faa8823978

build:
  skip: True # [osx] Probably won't work on OSX...
  number: 0

requirements:
  build:
    - zlib
    - armadillo
    - boost >=1.57
    - hdf5
    - lapack
    - openblas
    - pthread-stubs
    
  run:
    - zlib
    - lapack
    - openblas
    - boost >=1.57
    - armadillo
    - hdf5
    - pthread-stubs

test:
  commands:
    - seer --version

about:
  home: https://github.com/johnlees/seer
  license: GNU General Public License v2.0
  summary: sequence element (kmer) enrichment analysis