package:
  name: r-listenv
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.5.0"

source:
  fn: listenv_0.5.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/listenv_0.5.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/listenv/listenv_0.5.0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: R.rsp
requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('listenv')" # [not win]
    - "\"%R%\" -e \"library('listenv')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/HenrikBengtsson/listenv'

  license: LGPL (>= 2.1)
  summary: !!python/unicode 'List environments are environments that can be indexed similarly
    to lists, e.g. ''x <- listenv(); x[[2]] <- "b"; names(x)[2] <- "B"; print(x$B)''.'


# The original CRAN metadata for this package was:

# Package: listenv
# Version: 0.5.0
# Depends: R (>= 3.1.2)
# Suggests: R.rsp
# VignetteBuilder: R.rsp
# Title: Environments Behaving (Almost) as Lists
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Description: List environments are environments that can be indexed similarly to lists, e.g. 'x <- listenv(); x[[2]] <- "b"; names(x)[2] <- "B"; print(x$B)'.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# URL: https://github.com/HenrikBengtsson/listenv
# BugReports: https://github.com/HenrikBengtsson/listenv/issues
# NeedsCompilation: no
# Packaged: 2015-10-30 20:05:21 UTC; hb
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Repository: CRAN
# Date/Publication: 2015-10-31 00:16:07

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
