{% set version="0.6.0" %}

package:
  name: rapmap
  version: {{ version }}

source:
  url: https://github.com/COMBINE-lab/RapMap/archive/v{{ version }}.tar.gz
  sha256: b1654883cb69690e428143d1c735bd26a3de8d731e2ff16c3bf3152ed2caa03d

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - autoconf
  host:
    - zlib
    - bzip2
    - unzip
    - jemalloc >=5.1.0
  run:
    - jemalloc >=5.1.0
    - tbb
    - zlib
    - bzip2

build:
  number: 0
  #skip: True # [osx]

about:
  home: https://github.com/COMBINE-lab/RapMap
  license: GPL
  summary: Rapid sensitive and accurate read mapping via quasi-mapping

test:
  commands:
    - rapmap --help
