package:
  name: r-matrixstats
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.50.1"

source:
  fn: matrixStats_0.50.1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/matrixStats_0.50.1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/matrixStats/matrixStats_0.50.1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: base64enc, ggplot2, knitr, microbenchmark, R.devices, R.rsp
requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('matrixStats')" # [not win]
    - "\"%R%\" -e \"library('matrixStats')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/HenrikBengtsson/matrixStats'

  license: Artistic-2.0
  summary: !!python/unicode 'High-performing functions operating on rows and columns of matrices,
    e.g. col / rowMedians(), col / rowRanks(), and col / rowSds().  Functions optimized
    per data type and for subsetted calculations such that both memory usage and processing
    time is minimized.  There are also optimized vector-based methods, e.g. binMeans(),
    madDiff() and weightedMedians().'


# The original CRAN metadata for this package was:

# Package: matrixStats
# Version: 0.50.1
# Depends: R (>= 2.12.0)
# Imports: methods
# Suggests: base64enc, ggplot2, knitr, microbenchmark, R.devices, R.rsp
# VignetteBuilder: R.rsp
# Date: 2015-12-14
# Title: Functions that Apply to Rows and Columns of Matrices (and to Vectors)
# Authors@R: c( person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email="henrikb@braju.com"), person("Hector", "Corrada Bravo", role="ctb"), person("Robert", "Gentleman", role="ctb"), person("Ola", "Hossjer", role="ctb"), person("Harris", "Jaffee", role="ctb"), person("Dongcan", "Jiang", role="ctb"), person("Peter", "Langfelder", role="ctb"))
# Author: Henrik Bengtsson [aut, cre, cph], Hector Corrada Bravo [ctb], Robert Gentleman [ctb], Ola Hossjer [ctb], Harris Jaffee [ctb], Dongcan Jiang [ctb], Peter Langfelder [ctb]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Description: High-performing functions operating on rows and columns of matrices, e.g. col / rowMedians(), col / rowRanks(), and col / rowSds().  Functions optimized per data type and for subsetted calculations such that both memory usage and processing time is minimized.  There are also optimized vector-based methods, e.g. binMeans(), madDiff() and weightedMedians().
# License: Artistic-2.0
# LazyLoad: TRUE
# NeedsCompilation: yes
# ByteCompile: TRUE
# biocViews: Infrastructure, Statistics
# URL: https://github.com/HenrikBengtsson/matrixStats
# BugReports: https://github.com/HenrikBengtsson/matrixStats/issues
# Packaged: 2015-12-15 02:56:11 UTC; hb
# Repository: CRAN
# Date/Publication: 2015-12-15 09:27:16

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
