package:
  name: star
  version: "2.5.0c"
source:
  fn: 2.5.0c.tar.gz
  url: https://github.com/alexdobin/STAR/archive/2.5.0c.tar.gz
about:
  home: https://github.com/alexdobin/STAR
  license: GPLv3
  summary: An RNA-seq read aligner.
test:
  commands:
    - STAR --version
