package:
  name: bcbio-nextgen
  version: '0.9.5'

build:
  number: 1
  skip: True # [not py27]

source:
  fn: bcbio-nextgen-0.9.5.tar.gz
  url: https://pypi.python.org/packages/source/b/bcbio-nextgen/bcbio-nextgen-0.9.5.tar.gz
  #fn: bcbio-nextgen-acd79b4.tar.gz
  #url: https://github.com/chapmanb/bcbio-nextgen/archive/acd79b4.tar.gz

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - argparse [py26]
    - arrow
    - azure
    - bioblend
    - biopython
    - boto
    - click
    - cython
    - cyvcf2
    - fabric
    - fadapa
    - gffutils
    - ipyparallel
    - ipython-cluster-helper
    - joblib
    - logbook
    - lxml
    - matplotlib
    - msgpack-python
    - nose
    - numpy
    - openpyxl
    - openssl
    - pandas
    - path.py
    - patsy
    - pip
    - pycrypto
    - progressbar
    - psutil
    - python-dateutil
    - pybedtools
    - pysam
    - pyvcf
    - pyyaml
    - pyzmq
    - reportlab
    - requests
    - scikit-learn
    - scipy
    - seaborn
    - seqcluster
    - sh
    - sqlalchemy
    - statsmodels
    - tabulate
    - toolz
    - tornado
    
test:
  imports:
    - bcbio.distributed.ipython
    - bcbio.distributed.multi
    - bcbio.pipeline.main
    - bcbio.provenance.do

about:
  home: https://github.com/chapmanb/bcbio-nextgen
  license: MIT
  summary: Validated, scalable, community developed variant calling, RNA-seq and small RNA analysis
