package:
  name: bcbio-rnaseq
  version: 1.0.3

source:
  fn: bcbio-rnaseq
  url: https://github.com/roryk/bcbio.rnaseq/releases/download/v1.0.3/bcbio-rnaseq

build:
  number: 1

requirements:
  run:
    - java-jdk
    - r

test:
  commands:
    - bcbio-rnaseq --version

about:
  home: https://github.com/roryk/bcbio.rnaseq
  license: MIT
  summary: Report generation for bcbio-nextgen RNA-seq runs
