about:
    home: http://mgltools.scripps.edu/
    license_file: LICENSES
    summary: MGLTools is an program for visualization and analisys of molecular structures.
package:
    name: mgltools
    version: 1.5.6
build:
  number: 0
  skip: False
source:
    fn:  mgltools_x86_64Linux2_1.5.6.tar.gz                                                                             # [linux]
    url: http://mgltools.scripps.edu/downloads/downloads/tars/releases/REL1.5.6/mgltools_x86_64Linux2_1.5.6.tar.gz      # [linux]
    md5: e3f62852c4d442a292dedbe6c79540ca                                                                               # [linux]
requirements:
  build:
  run:
test:
    commands:
      - pmv --help