package:
  name: r-globals
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.6.0"

source:
  fn: globals_0.6.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/globals_0.6.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/globals/globals_0.6.0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r
    - r-codetools # [not win]

  run:
    - r
    - r-codetools # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('globals')" # [not win]
    - "\"%R%\" -e \"library('globals')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/HenrikBengtsson/globals'

  license: LGPL (>= 2.1)
  summary: !!python/unicode 'Identifies global ("unknown") objects in R expressions by code inspection
    using various strategies, e.g. conservative or liberal. The objective of this package
    is to make it as simple as possible to identify global objects for the purpose of
    exporting them in distributed compute environments.'


# The original CRAN metadata for this package was:

# Package: globals
# Version: 0.6.0
# Depends: R (>= 3.1.2)
# Imports: codetools
# Title: Identify Global Objects in R Expressions
# Authors@R: c( person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email="henrikb@braju.com"))
# Description: Identifies global ("unknown") objects in R expressions by code inspection using various strategies, e.g. conservative or liberal. The objective of this package is to make it as simple as possible to identify global objects for the purpose of exporting them in distributed compute environments.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# ByteCompile: TRUE
# URL: https://github.com/HenrikBengtsson/globals
# BugReports: https://github.com/HenrikBengtsson/globals/issues
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2015-12-12 15:03:09 UTC; hb
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Repository: CRAN
# Date/Publication: 2015-12-12 18:49:07

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
