about:
  home: https://github.com/lpantano/seqclsuter
  license: MIT
  summary: small RNA analysis from NGS data

package:
  name: seqcluster
  version: '1.1.13'

source:
  git_url: https://github.com/lpantano/seqcluster
  git_rev: deac8b3

build:
  number: 2
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - yaml
    - pysam >=0.8.1
    - pandas
    - pybedtools
    - progressbar
    - matplotlib

test:
  commands:
    - seqcluster cluster -h
  imports:
    - seqcluster
